type Question = {
  id: string;
  text: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  subject: 'math' | 'science' | 'history' | 'literature' | 'geography' | 'coding';
};

export const questionPool: Question[] = [
  // ================== MATHEMATICS ==================
  {
    id: 'math-b1',
    text: 'What is 5 + 7?',
    options: ['10', '11', '12', '13'],
    correctAnswer: '12',
    explanation: 'Adding 5 and 7 gives a sum of 12.',
    difficulty: 'beginner',
    subject: 'math',
  },
  {
    id: 'math-b2',
    text: 'What is the value of 3 × 4?',
    options: ['12', '7', '9', '15'],
    correctAnswer: '12',
    explanation: 'Multiplying 3 by 4 results in 12.',
    difficulty: 'beginner',
    subject: 'math',
  },
  {
    id: 'math-b3',
    text: 'What is half of 10?',
    options: ['3', '5', '7', '2'],
    correctAnswer: '5',
    explanation: 'Dividing 10 by 2 gives 5.',
    difficulty: 'beginner',
    subject: 'math',
  },
  {
    id: 'math-i1',
    text: 'Solve for x: 2x + 3 = 11',
    options: ['2', '3', '4', '5'],
    correctAnswer: '4',
    explanation: 'Subtract 3 from both sides: 2x = 8. Divide by 2: x = 4.',
    difficulty: 'intermediate',
    subject: 'math',
  },
  {
    id: 'math-i2',
    text: 'What is the area of a rectangle with length 6 and width 4?',
    options: ['20', '24', '10', '18'],
    correctAnswer: '24',
    explanation: 'Area = length × width = 6 × 4 = 24.',
    difficulty: 'intermediate',
    subject: 'math',
  },
  {
    id: 'math-i3',
    text: 'What is 2³?',
    options: ['6', '8', '4', '9'],
    correctAnswer: '8',
    explanation: '2³ means 2 × 2 × 2 = 8.',
    difficulty: 'intermediate',
    subject: 'math',
  },
  {
    id: 'math-a1',
    text: 'What is the value of sin(30°)?',
    options: ['0.5', '1', '0.866', '0.707'],
    correctAnswer: '0.5',
    explanation: 'The sine of 30° is 0.5, as per the unit circle or trigonometric tables.',
    difficulty: 'advanced',
    subject: 'math',
  },
  {
    id: 'math-a2',
    text: 'Solve for x: x² - 5x + 6 = 0',
    options: ['x = 2, 3', 'x = 1, 4', 'x = -2, -3', 'x = 0, 5'],
    correctAnswer: 'x = 2, 3',
    explanation: 'Factorize: (x - 2)(x - 3) = 0. Thus, x = 2 or x = 3.',
    difficulty: 'advanced',
    subject: 'math',
  },
  {
    id: 'math-a3',
    text: 'What is the derivative of x²?',
    options: ['2x', 'x', 'x²', '2'],
    correctAnswer: '2x',
    explanation: 'Using the power rule, the derivative of x² is 2x.',
    difficulty: 'advanced',
    subject: 'math',
  },
  {
    id: 'math-e1',
    text: 'Evaluate ∫(0 to 1) x² dx',
    options: ['1/3', '1/2', '1', '2/3'],
    correctAnswer: '1/3',
    explanation: 'The integral of x² is (x³)/3. Evaluate from 0 to 1: (1³)/3 - (0³)/3 = 1/3.',
    difficulty: 'expert',
    subject: 'math',
  },
  {
    id: 'math-e2',
    text: 'What is the sum of the first n terms of the geometric series 1 + 2 + 4 + ... + 2^(n-1)?',
    options: ['2^n - 1', '2^n', '2^(n+1) - 1', '2^(n-1)'],
    correctAnswer: '2^n - 1',
    explanation: 'The sum of a geometric series is (1 - r^n)/(1 - r). Here, r = 2, so sum = (1 - 2^n)/(1 - 2) = 2^n - 1.',
    difficulty: 'expert',
    subject: 'math',
  },
  {
    id: 'math-e3',
    text: 'What is the determinant of the matrix [[2, 1], [3, 4]]?',
    options: ['5', '7', '8', '11'],
    correctAnswer: '5',
    explanation: 'Determinant = (2 × 4) - (1 × 3) = 8 - 3 = 5.',
    difficulty: 'expert',
    subject: 'math',
  },
  {
    id: 'math-b4',
    text: 'What is 15 - 6?',
    options: ['9', '8', '7', '10'],
    correctAnswer: '9',
    explanation: 'Subtracting 6 from 15 gives 9.',
    difficulty: 'beginner',
    subject: 'math',
  },
  {
    id: 'math-i4',
    text: 'What is the perimeter of a square with side length 5?',
    options: ['15', '20', '25', '10'],
    correctAnswer: '20',
    explanation: 'Perimeter = 4 × side = 4 × 5 = 20.',
    difficulty: 'intermediate',
    subject: 'math',
  },
  {
    id: 'math-a4',
    text: 'What is log₂(8)?',
    options: ['2', '3', '4', '1'],
    correctAnswer: '3',
    explanation: 'log₂(8) = x means 2^x = 8. Since 2³ = 8, x = 3.',
    difficulty: 'advanced',
    subject: 'math',
  },

  // ================== SCIENCE ==================
  {
    id: 'sc-b1',
    text: 'What is H₂O commonly known as?',
    options: ['Hydrogen', 'Oxygen', 'Water', 'Carbon Dioxide'],
    correctAnswer: 'Water',
    explanation: 'H₂O is the chemical formula for water, consisting of two hydrogen atoms and one oxygen atom.',
    difficulty: 'beginner',
    subject: 'science',
  },
  {
    id: 'sc-b2',
    text: 'What is the primary source of energy for Earth?',
    options: ['Moon', 'Sun', 'Wind', 'Ocean'],
    correctAnswer: 'Sun',
    explanation: 'The Sun provides energy through sunlight, driving processes like photosynthesis and weather patterns.',
    difficulty: 'beginner',
    subject: 'science',
  },
  {
    id: 'sc-b3',
    text: 'Which state of matter has a definite shape and volume?',
    options: ['Gas', 'Liquid', 'Solid', 'Plasma'],
    correctAnswer: 'Solid',
    explanation: 'Solids have tightly packed particles, giving them a fixed shape and volume.',
    difficulty: 'beginner',
    subject: 'science',
  },
  {
    id: 'sc-i1',
    text: 'Which gas do plants absorb from the atmosphere for photosynthesis?',
    options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
    correctAnswer: 'Carbon Dioxide',
    explanation: 'Plants use carbon dioxide (CO₂) during photosynthesis to produce glucose and oxygen.',
    difficulty: 'intermediate',
    subject: 'science',
  },
  {
    id: 'sc-i2',
    text: 'What is the chemical symbol for Gold?',
    options: ['Au', 'Ag', 'Fe', 'Cu'],
    correctAnswer: 'Au',
    explanation: 'Au is the symbol for Gold on the periodic table, derived from its Latin name, Aurum.',
    difficulty: 'intermediate',
    subject: 'science',
  },
  {
    id: 'sc-i3',
    text: 'Which planet is closest to the Sun?',
    options: ['Venus', 'Earth', 'Mercury', 'Mars'],
    correctAnswer: 'Mercury',
    explanation: 'Mercury is the closest planet to the Sun, orbiting at an average distance of 58 million kilometers.',
    difficulty: 'intermediate',
    subject: 'science',
  },
  {
    id: 'sc-a1',
    text: 'What is the atomic number of Gold?',
    options: ['47', '79', '82', '118'],
    correctAnswer: '79',
    explanation: 'The atomic number of Gold is 79, indicating it has 79 protons in its nucleus.',
    difficulty: 'advanced',
    subject: 'science',
  },
  {
    id: 'sc-a2',
    text: 'What is the primary source of energy in nuclear power plants?',
    options: ['Fusion', 'Fission', 'Combustion', 'Geothermal'],
    correctAnswer: 'Fission',
    explanation: 'Nuclear power plants use nuclear fission, splitting atoms like uranium-235, to release energy.',
    difficulty: 'advanced',
    subject: 'science',
  },
  {
    id: 'sc-a3',
    text: 'What gas, discovered on the sun before Earth, is the second most abundant element in the universe?',
    options: ['Hydrogen', 'Helium', 'Oxygen', 'Nitrogen'],
    correctAnswer: 'Helium',
    explanation: 'Helium was first detected in the Sun’s spectrum during a solar eclipse in 1868 and is the second most abundant element after hydrogen.',
    difficulty: 'advanced',
    subject: 'science',
  },
  {
    id: 'sc-e1',
    text: 'What is the primary source of energy for Earth’s climate system?',
    options: ['Solar radiation', 'Geothermal heat', 'Tidal forces', 'Cosmic rays'],
    correctAnswer: 'Solar radiation',
    explanation: 'Solar radiation drives Earth’s climate by heating the atmosphere, oceans, and land, influencing weather patterns.',
    difficulty: 'expert',
    subject: 'science',
  },
  {
    id: 'sc-e2',
    text: 'What is the primary source of energy for Earth’s climate system?',
    options: ['Solar radiation', 'Geothermal heat', 'Tidal forces', 'Cosmic rays'],
    correctAnswer: 'Solar radiation',
    explanation: 'Solar radiation drives Earth’s climate by heating the atmosphere, oceans, and land, influencing weather patterns.',
    difficulty: 'expert',
    subject: 'science',
  },
  {
    id: 'sc-e3',
    text: 'What is the name of the particle that mediates the strong nuclear force?',
    options: ['Photon', 'Gluon', 'Boson', 'Quark'],
    correctAnswer: 'Gluon',
    explanation: 'Gluons are elementary particles that mediate the strong nuclear force, binding quarks together within protons and neutrons.',
    difficulty: 'expert',
    subject: 'science',
  },
  {
    id: 'sc-b4',
    text: 'What organ pumps blood in the human body?',
    options: ['Lungs', 'Heart', 'Liver', 'Kidneys'],
    correctAnswer: 'Heart',
    explanation: 'The heart pumps blood, circulating oxygen and nutrients throughout the body.',
    difficulty: 'beginner',
    subject: 'science',
  },
  {
    id: 'sc-i4',
    text: 'What is the boiling point of water at sea level?',
    options: ['90°C', '100°C', '110°C', '80°C'],
    correctAnswer: '100°C',
    explanation: 'At sea level, water boils at 100°C under standard atmospheric pressure.',
    difficulty: 'intermediate',
    subject: 'science',
  },
  {
    id: 'sc-a4',
    text: 'What is the primary gas in Earth’s atmosphere?',
    options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Argon'],
    correctAnswer: 'Nitrogen',
    explanation: 'Nitrogen makes up about 78% of Earth’s atmosphere by volume.',
    difficulty: 'advanced',
    subject: 'science',
  },

  // ================== HISTORY ==================
  {
    id: 'hi-b1',
    text: 'In which year did World War II end?',
    options: ['1943', '1945', '1947', '1950'],
    correctAnswer: '1945',
    explanation: 'World War II ended on September 2, 1945, with Japan’s surrender.',
    difficulty: 'beginner',
    subject: 'history',
  },
  {
    id: 'hi-b2',
    text: 'Who was the first person to walk on the Moon?',
    options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'],
    correctAnswer: 'Neil Armstrong',
    explanation: 'Neil Armstrong walked on the Moon on July 20, 1969, during the Apollo 11 mission.',
    difficulty: 'beginner',
    subject: 'history',
  },
  {
    id: 'hi-b3',
    text: 'What ancient structure is one of the Seven Wonders of the World?',
    options: ['Eiffel Tower', 'Great Wall of China', 'Pyramid of Giza', 'Colosseum'],
    correctAnswer: 'Pyramid of Giza',
    explanation: 'The Great Pyramid of Giza, built around 2600 BCE, is one of the Seven Wonders of the Ancient World.',
    difficulty: 'beginner',
    subject: 'history',
  },
  {
    id: 'hi-i1',
    text: 'Who was the first President of the United States?',
    options: ['Thomas Jefferson', 'John Adams', 'George Washington', 'Benjamin Franklin'],
    correctAnswer: 'George Washington',
    explanation: 'George Washington served as the first U.S. President from 1789 to 1797.',
    difficulty: 'intermediate',
    subject: 'history',
  },
  {
    id: 'hi-i2',
    text: 'Which empire built the Colosseum in Rome?',
    options: ['Byzantine', 'Roman', 'Ottoman', 'Greek'],
    correctAnswer: 'Roman',
    explanation: 'The Colosseum was constructed by the Roman Empire, completed in 80 CE under Emperor Titus.',
    difficulty: 'intermediate',
    subject: 'history',
  },
  {
    id: 'hi-i3',
    text: 'What event marked the start of the French Revolution?',
    options: ['Storming of the Bastille', 'Execution of Louis XVI', 'Reign of Terror', 'Napoleon’s coup'],
    correctAnswer: 'Storming of the Bastille',
    explanation: 'The storming of the Bastille on July 14, 1789, symbolized the start of the French Revolution.',
    difficulty: 'intermediate',
    subject: 'history',
  },
  {
    id: 'hi-a1',
    text: 'Which ancient civilization built the Machu Picchu complex?',
    options: ['Aztec', 'Maya', 'Inca', 'Olmec'],
    correctAnswer: 'Inca',
    explanation: 'Machu Picchu was built by the Inca Empire in the 15th century in modern-day Peru.',
    difficulty: 'advanced',
    subject: 'history',
  },
  {
    id: 'hi-a2',
    text: 'Who was the leader of the Soviet Union during World War II?',
    options: ['Vladimir Lenin', 'Joseph Stalin', 'Leon Trotsky', 'Nikita Khrushchev'],
    correctAnswer: 'Joseph Stalin',
    explanation: 'Joseph Stalin led the Soviet Union from the mid-1920s until his death in 1953, including during World War II.',
    difficulty: 'advanced',
    subject: 'history',
  },
  {
    id: 'hi-a3',
    text: 'What was the name of the trade route connecting Europe and Asia in the Middle Ages?',
    options: ['Spice Route', 'Silk Road', 'Amber Road', 'Incense Route'],
    correctAnswer: 'Silk Road',
    explanation: 'The Silk Road was a network of trade routes connecting Europe and Asia, facilitating cultural and economic exchange.',
    difficulty: 'advanced',
    subject: 'history',
  },
  {
    id: 'hi-e1',
    text: 'Which battle in 1066 marked the Norman conquest of England?',
    options: ['Battle of Agincourt', 'Battle of Hastings', 'Battle of Bosworth', 'Battle of Bannockburn'],
    correctAnswer: 'Battle of Hastings',
    explanation: 'The Battle of Hastings in 1066 resulted in William the Conqueror’s victory, leading to the Norman conquest of England.',
    difficulty: 'expert',
    subject: 'history',
  },
  {
    id: 'hi-e2',
    text: 'What was the primary cause of the Opium Wars between Britain and China?',
    options: ['Territorial disputes', 'Trade imbalances', 'Religious conflicts', 'Dynastic succession'],
    correctAnswer: 'Trade imbalances',
    explanation: 'The Opium Wars (1839-1860) arose from Britain’s opium trade to offset trade imbalances with China, leading to conflict.',
    difficulty: 'expert',
    subject: 'history',
  },
  {
    id: 'hi-e3',
    text: 'Which Mesoamerican civilization used a 365-day solar calendar?',
    options: ['Olmec', 'Maya', 'Aztec', 'Inca'],
    correctAnswer: 'Maya',
    explanation: 'The Maya developed a sophisticated 365-day solar calendar, known as the Haab’, alongside a 260-day ritual calendar.',
    difficulty: 'expert',
    subject: 'history',
  },
  {
    id: 'hi-b4',
    text: 'What was the name of the ship that carried the Pilgrims to America in 1620?',
    options: ['Santa Maria', 'Mayflower', 'Nina', 'Pinta'],
    correctAnswer: 'Mayflower',
    explanation: 'The Mayflower carried the Pilgrims to Plymouth, Massachusetts, in 1620, founding one of the earliest English colonies.',
    difficulty: 'beginner',
    subject: 'history',
  },
  {
    id: 'hi-i4',
    text: 'Which queen ruled England during the defeat of the Spanish Armada?',
    options: ['Mary I', 'Elizabeth I', 'Victoria', 'Anne'],
    correctAnswer: 'Elizabeth I',
    explanation: 'Elizabeth I was queen when England defeated the Spanish Armada in 1588, a pivotal moment in English history.',
    difficulty: 'intermediate',
    subject: 'history',
  },
  {
    id: 'hi-a4',
    text: 'What was the primary purpose of the Magna Carta signed in 1215?',
    options: ['Establish parliament', 'Limit royal power', 'Grant land rights', 'Regulate trade'],
    correctAnswer: 'Limit royal power',
    explanation: 'The Magna Carta, signed by King John, limited royal authority and established legal protections for nobles.',
    difficulty: 'advanced',
    subject: 'history',
  },

  // ================== LITERATURE ==================
  {
    id: 'lit-b1',
    text: 'Who wrote "Romeo and Juliet"?',
    options: ['William Shakespeare', 'Jane Austen', 'Charles Dickens', 'Mark Twain'],
    correctAnswer: 'William Shakespeare',
    explanation: 'William Shakespeare wrote the tragic play "Romeo and Juliet" around 1595.',
    difficulty: 'beginner',
    subject: 'literature',
  },
  {
    id: 'lit-b2',
    text: 'What is the name of the wizard school in the Harry Potter series?',
    options: ['Durmstrang', 'Beauxbatons', 'Hogwarts', 'Ilvermorny'],
    correctAnswer: 'Hogwarts',
    explanation: 'Hogwarts School of Witchcraft and Wizardry is the primary setting for J.K. Rowling’s Harry Potter series.',
    difficulty: 'beginner',
    subject: 'literature',
  },
  {
    id: 'lit-b3',
    text: 'Who is the author of "Pride and Prejudice"?',
    options: ['Charlotte Brontë', 'Jane Austen', 'Emily Dickinson', 'Mary Shelley'],
    correctAnswer: 'Jane Austen',
    explanation: 'Jane Austen wrote the classic novel "Pride and Prejudice," published in 1813.',
    difficulty: 'beginner',
    subject: 'literature',
  },
  {
    id: 'lit-i1',
    text: 'Which Shakespeare play features the character Ophelia?',
    options: ['Macbeth', 'Hamlet', 'Romeo and Juliet', 'Othello'],
    correctAnswer: 'Hamlet',
    explanation: 'Ophelia is a character in Shakespeare’s "Hamlet," known for her tragic fate.',
    difficulty: 'intermediate',
    subject: 'literature',
  },
  {
    id: 'lit-i2',
    text: 'Who wrote the epic poem "The Odyssey"?',
    options: ['Virgil', 'Homer', 'Dante', 'Ovid'],
    correctAnswer: 'Homer',
    explanation: 'Homer, an ancient Greek poet, is credited with writing "The Odyssey," an epic about Odysseus’s journey.',
    difficulty: 'intermediate',
    subject: 'literature',
  },
  {
    id: 'lit-i3',
    text: 'What is the name of the fictional whale in Herman Melville’s novel?',
    options: ['Moby Dick', 'Shamu', 'Jonah', 'Ishmael'],
    correctAnswer: 'Moby Dick',
    explanation: '"Moby-Dick" is the white whale pursued by Captain Ahab in Melville’s 1851 novel.',
    difficulty: 'intermediate',
    subject: 'literature',
  },
  {
    id: 'lit-a1',
    text: 'Which novel by George Orwell features a dystopian society ruled by Big Brother?',
    options: ['Animal Farm', '1984', 'Brave New World', 'Fahrenheit 451'],
    correctAnswer: '1984',
    explanation: '"1984" depicts a totalitarian society under constant surveillance by Big Brother.',
    difficulty: 'advanced',
    subject: 'literature',
  },
  {
    id: 'lit-a2',
    text: 'Who wrote the "Divine Comedy"?',
    options: ['Geoffrey Chaucer', 'Dante Alighieri', 'John Milton', 'William Blake'],
    correctAnswer: 'Dante Alighieri',
    explanation: 'Dante Alighieri wrote the "Divine Comedy," an epic poem describing a journey through Hell, Purgatory, and Paradise.',
    difficulty: 'advanced',
    subject: 'literature',
  },
  {
    id: 'lit-a3',
    text: 'Which Brontë sister wrote "Wuthering Heights"?',
    options: ['Charlotte', 'Emily', 'Anne', 'Maria'],
    correctAnswer: 'Emily',
    explanation: 'Emily Brontë wrote "Wuthering Heights," a passionate novel about Heathcliff and Catherine, published in 1847.',
    difficulty: 'advanced',
    subject: 'literature',
  },
  {
    id: 'lit-e1',
    text: 'What is the name of the fictional African country in Chinua Achebe’s "Things Fall Apart"?',
    options: ['Umuofia', 'Wakanda', 'Zamunda', 'Narnia'],
    correctAnswer: 'Umuofia',
    explanation: 'Umuofia is the Igbo village setting in Achebe’s novel, exploring pre-colonial African culture and colonialism’s impact.',
    difficulty: 'expert',
    subject: 'literature',
  },
  {
    id: 'lit-e2',
    text: 'Which Russian author wrote "Crime and Punishment"?',
    options: ['Leo Tolstoy', 'Fyodor Dostoevsky', 'Anton Chekhov', 'Ivan Turgenev'],
    correctAnswer: 'Fyodor Dostoevsky',
    explanation: 'Fyodor Dostoevsky wrote "Crime and Punishment," a psychological novel about guilt and redemption, published in 1866.',
    difficulty: 'expert',
    subject: 'literature',
  },
  {
    id: 'lit-e3',
    text: 'What is the name of the monster in Mary Shelley’s "Frankenstein"?',
    options: ['Dracula', 'The Creature', 'Wolfman', 'Igor'],
    correctAnswer: 'The Creature',
    explanation: 'In "Frankenstein," the monster is referred to as "The Creature," created by Victor Frankenstein.',
    difficulty: 'expert',
    subject: 'literature',
  },
  {
    id: 'lit-b4',
    text: 'Who wrote the children’s book "The Cat in the Hat"?',
    options: ['Dr. Seuss', 'Roald Dahl', 'J.K. Rowling', 'E.B. White'],
    correctAnswer: 'Dr. Seuss',
    explanation: 'Dr. Seuss wrote "The Cat in the Hat," a beloved children’s book published in 1957.',
    difficulty: 'beginner',
    subject: 'literature',
  },
  {
    id: 'lit-i4',
    text: 'Which novel features the character Atticus Finch?',
    options: ['To Kill a Mockingbird', 'The Great Gatsby', 'Catcher in the Rye', 'Lord of the Flies'],
    correctAnswer: 'To Kill a Mockingbird',
    explanation: 'Atticus Finch is the moral lawyer in Harper Lee’s "To Kill a Mockingbird," published in 1960.',
    difficulty: 'intermediate',
    subject: 'literature',
  },
  {
    id: 'lit-a4',
    text: 'What is the name of the hobbit protagonist in J.R.R. Tolkien’s "The Hobbit"?',
    options: ['Frodo Baggins', 'Samwise Gamgee', 'Bilbo Baggins', 'Pippin Took'],
    correctAnswer: 'Bilbo Baggins',
    explanation: 'Bilbo Baggins is the adventurous hobbit protagonist in "The Hobbit," published in 1937.',
    difficulty: 'advanced',
    subject: 'literature',
  },

  // ================== GEOGRAPHY ==================
  {
    id: 'geo-b1',
    text: 'What is the capital of France?',
    options: ['London', 'Paris', 'Berlin', 'Madrid'],
    correctAnswer: 'Paris',
    explanation: 'Paris is the capital city of France, known for landmarks like the Eiffel Tower.',
    difficulty: 'beginner',
    subject: 'geography',
  },
  {
    id: 'geo-b2',
    text: 'Which continent is the largest by land area?',
    options: ['Africa', 'Asia', 'Australia', 'Europe'],
    correctAnswer: 'Asia',
    explanation: 'Asia is the largest continent, covering about 44.58 million square kilometers.',
    difficulty: 'beginner',
    subject: 'geography',
  },
  {
    id: 'geo-b3',
    text: 'What is the longest river in the world?',
    options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    correctAnswer: 'Nile',
    explanation: 'The Nile River, approximately 6,650 km long, is considered the longest river globally.',
    difficulty: 'beginner',
    subject: 'geography',
  },
  {
    id: 'geo-i1',
    text: 'Which country is home to the kangaroo?',
    options: ['South Africa', 'Brazil', 'Australia', 'New Zealand'],
    correctAnswer: 'Australia',
    explanation: 'Kangaroos are marsupials native to Australia, found in its grasslands and forests.',
    difficulty: 'intermediate',
    subject: 'geography',
  },
  {
    id: 'geo-i2',
    text: 'What is the smallest country in the world by land area?',
    options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctAnswer: 'Vatican City',
    explanation: 'Vatican City, at 0.49 square kilometers, is the smallest country by land area.',
    difficulty: 'intermediate',
    subject: 'geography',
  },
  {
    id: 'geo-i3',
    text: 'Which mountain is the highest in the world?',
    options: ['K2', 'Kangchenjunga', 'Everest', 'Makalu'],
    correctAnswer: 'Everest',
    explanation: 'Mount Everest, at 8,848 meters, is the highest mountain above sea level.',
    difficulty: 'intermediate',
    subject: 'geography',
  },
  {
    id: 'geo-a1',
    text: 'What is the largest desert in the world?',
    options: ['Sahara', 'Gobi', 'Kalahari', 'Antarctic'],
    correctAnswer: 'Antarctic',
    explanation: 'The Antarctic Desert, covering 13.8 million square kilometers, is the largest desert, classified due to its extremely low precipitation.',
    difficulty: 'advanced',
    subject: 'geography',
  },
  {
    id: 'geo-a2',
    text: 'Which country has the most deserts in the world?',
    options: ['Australia', 'China', 'United States', 'Algeria'],
    correctAnswer: 'Australia',
    explanation: 'Australia has the most desert coverage by percentage, with about 70% of its landmass classified as desert or semi-arid.',
    difficulty: 'advanced',
    subject: 'geography',
  },
  {
    id: 'geo-a3',
    text: 'What is the name of the strait separating Europe and Africa?',
    options: ['Bering Strait', 'Strait of Gibraltar', 'Strait of Hormuz', 'English Channel'],
    correctAnswer: 'Strait of Gibraltar',
    explanation: 'The Strait of Gibraltar connects the Atlantic Ocean to the Mediterranean Sea, separating Spain from Morocco.',
    difficulty: 'advanced',
    subject: 'geography',
  },
  {
    id: 'geo-e1',
    text: 'Which country has the longest coastline in the world?',
    options: ['Russia', 'Canada', 'Australia', 'Indonesia'],
    correctAnswer: 'Canada',
    explanation: 'Canada has the longest coastline, approximately 243,042 km, due to its extensive Arctic and Atlantic shores.',
    difficulty: 'expert',
    subject: 'geography',
  },
  {
    id: 'geo-e2',
    text: 'What is the name of the tectonic plate that includes most of South America?',
    options: ['Pacific Plate', 'Nazca Plate', 'South American Plate', 'Caribbean Plate'],
    correctAnswer: 'South American Plate',
    explanation: 'The South American Plate is the tectonic plate underlying most of South America and parts of the Atlantic Ocean.',
    difficulty: 'expert',
    subject: 'geography',
  },
  {
    id: 'geo-e3',
    text: 'Which African country is completely surrounded by South Africa?',
    options: ['Lesotho', 'Swaziland', 'Botswana', 'Namibia'],
    correctAnswer: 'Lesotho',
    explanation: 'Lesotho is an enclave country, entirely surrounded by South Africa, making it one of the few countries fully within another.',
    difficulty: 'expert',
    subject: 'geography',
  },
  {
    id: 'geo-b4',
    text: 'What is the capital of Brazil?',
    options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'],
    correctAnswer: 'Brasília',
    explanation: 'Brasília is the capital of Brazil, designed as a planned city and established in 1960.',
    difficulty: 'beginner',
    subject: 'geography',
  },
  {
    id: 'geo-i4',
    text: 'Which ocean is the largest?',
    options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctAnswer: 'Pacific',
    explanation: 'The Pacific Ocean is the largest, covering about 155.6 million square kilometers.',
    difficulty: 'intermediate',
    subject: 'geography',
  },
  {
    id: 'geo-a4',
    text: 'What is the name of the largest lake in Africa?',
    options: ['Lake Tanganyika', 'Lake Malawi', 'Lake Victoria', 'Lake Chad'],
    correctAnswer: 'Lake Victoria',
    explanation: 'Lake Victoria, covering about 68,800 square kilometers, is Africa’s largest lake and the second-largest freshwater lake globally.',
    difficulty: 'advanced',
    subject: 'geography',
  },

  // ================== CODING ==================
  {
    id: 'cod-b1',
    text: 'What does "HTML" stand for?',
    options: ['Hyper Text Markup Language', 'High Text Machine Language', 'Hyperlink Text Management Language', 'Hyper Transfer Markup Language'],
    correctAnswer: 'Hyper Text Markup Language',
    explanation: 'HTML is the standard language for creating web pages, structuring content with tags.',
    difficulty: 'beginner',
    subject: 'coding',
  },
  {
    id: 'cod-b2',
    text: 'Which symbol is used for comments in Python?',
    options: ['//', '#', '/*', '--'],
    correctAnswer: '#',
    explanation: 'In Python, the # symbol is used to indicate a single-line comment, ignored by the interpreter.',
    difficulty: 'beginner',
    subject: 'coding',
  },
  {
    id: 'cod-b3',
    text: 'What is the output of print("Hello, World!") in Python?',
    options: ['Hello World', 'Hello, World!', 'hello world', 'Error'],
    correctAnswer: 'Hello, World!',
    explanation: 'The print() function in Python outputs the specified string, including punctuation, to the console.',
    difficulty: 'beginner',
    subject: 'coding',
  },
  {
    id: 'cod-i1',
    text: 'What is the correct syntax for a CSS rule?',
    options: ['selector { property: value; }', 'property: value { selector; }', 'selector: property { value; }', '{ selector: property } value;'],
    correctAnswer: 'selector { property: value; }',
    explanation: 'A CSS rule consists of a selector followed by a declaration block with property-value pairs, e.g., p { color: blue; }.',
    difficulty: 'intermediate',
    subject: 'coding',
  },
  {
    id: 'cod-i2',
    text: 'In JavaScript, which method adds an element to the end of an array?',
    options: ['pop()', 'push()', 'shift()', 'unshift()'],
    correctAnswer: 'push()',
    explanation: 'The push() method adds one or more elements to the end of an array and returns the new length.',
    difficulty: 'intermediate',
    subject: 'coding',
  },
  {
    id: 'cod-i3',
    text: 'What does SQL stand for?',
    options: ['Standard Query Language', 'Structured Query Language', 'Sequential Query Language', 'Systematic Query Language'],
    correctAnswer: 'Structured Query Language',
    explanation: 'SQL is a language used for managing and querying relational databases.',
    difficulty: 'intermediate',
    subject: 'coding',
  },
  {
    id: 'cod-a1',
    text: 'What is the time complexity of a binary search algorithm?',
    options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'],
    correctAnswer: 'O(log n)',
    explanation: 'Binary search has a time complexity of O(log n) as it divides the search space in half with each step.',
    difficulty: 'advanced',
    subject: 'coding',
  },
  {
    id: 'cod-a2',
    text: 'In Python, what is the output of [1, 2, 3][1:3]?',
    options: ['[1, 2]', '[2, 3]', '[1, 3]', '[2]'],
    correctAnswer: '[2, 3]',
    explanation: 'Slicing [1:3] returns elements from index 1 up to (but not including) index 3, so [2, 3].',
    difficulty: 'advanced',
    subject: 'coding',
  },
  {
    id: 'cod-a3',
    text: 'What does the "S" in HTTPS stand for?',
    options: ['Secure', 'System', 'Standard', 'Service'],
    correctAnswer: 'Secure',
    explanation: 'HTTPS stands for HyperText Transfer Protocol Secure, using encryption for secure communication.',
    difficulty: 'advanced',
    subject: 'coding',
  },
  {
    id: 'cod-e1',
    text: 'What is a closure in JavaScript?',
    options: ['A loop that never terminates', 'A function with access to its parent’s scope', 'A method to lock variables', 'A way to bind this keyword'],
    correctAnswer: 'A function with access to its parent’s scope',
    explanation: 'A closure is a function that retains access to its lexical scope’s variables, even when executed outside that scope.',
    difficulty: 'expert',
    subject: 'coding',
  },
  {
    id: 'cod-e2',
    text: 'What is the purpose of a Docker container?',
    options: ['To compile code', 'To package and run applications', 'To manage databases', 'To optimize network traffic'],
    correctAnswer: 'To package and run applications',
    explanation: 'Docker containers package applications with their dependencies, ensuring consistent execution across environments.',
    difficulty: 'expert',
    subject: 'coding',
  },
  {
    id: 'cod-e3',
    text: 'In Git, what does the command "git merge" do?',
    options: ['Deletes a branch', 'Combines multiple branches', 'Creates a new branch', 'Reverts changes'],
    correctAnswer: 'Combines multiple branches',
    explanation: 'git merge integrates changes from one branch into another, combining their histories.',
    difficulty: 'expert',
    subject: 'coding',
  },
  {
    id: 'cod-b4',
    text: 'What is the file extension for Python files?',
    options: ['.js', '.py', '.html', '.css'],
    correctAnswer: '.py',
    explanation: 'Python source code files use the .py extension.',
    difficulty: 'beginner',
    subject: 'coding',
  },
  {
    id: 'cod-i4',
    text: 'What is the purpose of a "for" loop in programming?',
    options: ['To declare variables', 'To repeat code a set number of times', 'To handle errors', 'To define functions'],
    correctAnswer: 'To repeat code a set number of times',
    explanation: 'A for loop iterates over a sequence or range, executing code a specified number of times.',
    difficulty: 'intermediate',
    subject: 'coding',
  },
  {
    id: 'cod-a4',
    text: 'What is a REST API?',
    options: ['A database management system', 'A protocol for network security', 'An interface for web services', 'A type of programming language'],
    correctAnswer: 'An interface for web services',
    explanation: 'A REST API (Representational State Transfer) allows systems to communicate over HTTP using standard web protocols.',
    difficulty: 'advanced',
    subject: 'coding',
  },
];

export function getQuestionsBySubject(subject: string, difficulty: string) {
  return questionPool
    .filter(q => q.subject === subject && (difficulty === 'all' || q.difficulty === difficulty))
    .sort(() => 0.5 - Math.random())
    .slice(0, 15); // Return 15 questions
}

export function getSubjectDetails(subject: string) {
  const subjects: Record<string, { title: string; description: string; icon: string }> = {
    math: {
      title: 'Mathematics',
      description: 'Test your skills in numbers, equations, and logic',
      icon: '∑',
    },
    science: {
      title: 'Science',
      description: 'Explore questions about the natural world',
      icon: '⚗️',
    },
    history: {
      title: 'History',
      description: 'Journey through time with historical questions',
      icon: '🏛️',
    },
    literature: {
      title: 'Literature',
      description: 'Dive into books, authors, and literary works',
      icon: '📚',
    },
    geography: {
      title: 'Geography',
      description: 'Discover places, maps, and cultures',
      icon: '🌍',
    },
    coding: {
      title: 'Coding',
      description: 'Challenge your programming knowledge',
      icon: '💻',
    },
  };
  
  return subjects[subject];
}